// <auto-generated />
using System;
using ExakisNeliteTSP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExakisNeliteTSP.Migrations
{
    [DbContext(typeof(TspDbContext))]
    [Migration("20250918091205_Reseed_Tjm_Full")]
    partial class Reseed_Tjm_Full
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectConsultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ProjectConsultants");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfilRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeJh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cjm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("FraisDeplacementSiCession")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal?>("Prcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Profil")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TciOverPrcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tjm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProfilRows");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfileMonthly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeJh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProfilRowId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfilRowId");

                    b.HasIndex("ProjectId", "ProfilRowId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ProjectProfileMonthlies");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyDirector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchitectCds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchitectInternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackProjectManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<decimal?>("ContractAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractBackAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractCaBack")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("ProjectLead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposalRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RemiseTjmPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("SalesRep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.ProjectTjmItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tjm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Category", "Profile", "Location")
                        .IsUnique();

                    b.ToTable("ProjectTjmItems");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.ReferentielTjmItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Tjm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Profile", "Location")
                        .IsUnique();

                    b.ToTable("ReferentielTjmItems");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Consultant Junior",
                            Tjm = 500m
                        },
                        new
                        {
                            Id = 1001,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Consultant Junior",
                            Tjm = 300m
                        },
                        new
                        {
                            Id = 1002,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Consultant Junior",
                            Tjm = 435m
                        },
                        new
                        {
                            Id = 1003,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Consultant Junior",
                            Tjm = 261m
                        },
                        new
                        {
                            Id = 1010,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Consultant",
                            Tjm = 583m
                        },
                        new
                        {
                            Id = 1011,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Consultant",
                            Tjm = 350m
                        },
                        new
                        {
                            Id = 1012,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Consultant",
                            Tjm = 482m
                        },
                        new
                        {
                            Id = 1013,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Consultant",
                            Tjm = 289m
                        },
                        new
                        {
                            Id = 1020,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Consultant confirmé",
                            Tjm = 717m
                        },
                        new
                        {
                            Id = 1021,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Consultant confirmé",
                            Tjm = 430m
                        },
                        new
                        {
                            Id = 1022,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Consultant confirmé",
                            Tjm = 567m
                        },
                        new
                        {
                            Id = 1023,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Consultant confirmé",
                            Tjm = 340m
                        },
                        new
                        {
                            Id = 1030,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Expert",
                            Tjm = 792m
                        },
                        new
                        {
                            Id = 1031,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Expert",
                            Tjm = 475m
                        },
                        new
                        {
                            Id = 1032,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Expert",
                            Tjm = 667m
                        },
                        new
                        {
                            Id = 1033,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Expert",
                            Tjm = 400m
                        },
                        new
                        {
                            Id = 1040,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Expert senior",
                            Tjm = 842m
                        },
                        new
                        {
                            Id = 1041,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Expert senior",
                            Tjm = 505m
                        },
                        new
                        {
                            Id = 1042,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Expert senior",
                            Tjm = 767m
                        },
                        new
                        {
                            Id = 1043,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Expert senior",
                            Tjm = 460m
                        },
                        new
                        {
                            Id = 1050,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Architecte",
                            Tjm = 842m
                        },
                        new
                        {
                            Id = 1051,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Architecte",
                            Tjm = 505m
                        },
                        new
                        {
                            Id = 1052,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Architecte",
                            Tjm = 697m
                        },
                        new
                        {
                            Id = 1053,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Architecte",
                            Tjm = 418m
                        },
                        new
                        {
                            Id = 1060,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Architecte Senior",
                            Tjm = 917m
                        },
                        new
                        {
                            Id = 1061,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Architecte Senior",
                            Tjm = 550m
                        },
                        new
                        {
                            Id = 1062,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Architecte Senior",
                            Tjm = 833m
                        },
                        new
                        {
                            Id = 1063,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Architecte Senior",
                            Tjm = 500m
                        },
                        new
                        {
                            Id = 1070,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Chef de Projet",
                            Tjm = 755m
                        },
                        new
                        {
                            Id = 1071,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Chef de Projet",
                            Tjm = 453m
                        },
                        new
                        {
                            Id = 1072,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Chef de Projet",
                            Tjm = 625m
                        },
                        new
                        {
                            Id = 1073,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Chef de Projet",
                            Tjm = 375m
                        },
                        new
                        {
                            Id = 1080,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Chef de Projet Senior",
                            Tjm = 883m
                        },
                        new
                        {
                            Id = 1081,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Chef de Projet Senior",
                            Tjm = 530m
                        },
                        new
                        {
                            Id = 1082,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Chef de Projet Senior",
                            Tjm = 718m
                        },
                        new
                        {
                            Id = 1083,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Chef de Projet Senior",
                            Tjm = 431m
                        },
                        new
                        {
                            Id = 1090,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Directeur de projet",
                            Tjm = 983m
                        },
                        new
                        {
                            Id = 1091,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Directeur de projet",
                            Tjm = 590m
                        },
                        new
                        {
                            Id = 1092,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Directeur de projet",
                            Tjm = 867m
                        },
                        new
                        {
                            Id = 1093,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Directeur de projet",
                            Tjm = 520m
                        },
                        new
                        {
                            Id = 1100,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Consultant Fonctionnel",
                            Tjm = 648m
                        },
                        new
                        {
                            Id = 1101,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Consultant Fonctionnel",
                            Tjm = 389m
                        },
                        new
                        {
                            Id = 1102,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Consultant Fonctionnel",
                            Tjm = 505m
                        },
                        new
                        {
                            Id = 1103,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Consultant Fonctionnel",
                            Tjm = 303m
                        },
                        new
                        {
                            Id = 1110,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Consultant Fonctionnel Senior",
                            Tjm = 700m
                        },
                        new
                        {
                            Id = 1111,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Consultant Fonctionnel Senior",
                            Tjm = 420m
                        },
                        new
                        {
                            Id = 1112,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Consultant Fonctionnel Senior",
                            Tjm = 600m
                        },
                        new
                        {
                            Id = 1113,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Consultant Fonctionnel Senior",
                            Tjm = 360m
                        },
                        new
                        {
                            Id = 1120,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Expert Fonctionnel",
                            Tjm = 775m
                        },
                        new
                        {
                            Id = 1121,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Expert Fonctionnel",
                            Tjm = 465m
                        },
                        new
                        {
                            Id = 1122,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Expert Fonctionnel",
                            Tjm = 683m
                        },
                        new
                        {
                            Id = 1123,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Expert Fonctionnel",
                            Tjm = 410m
                        },
                        new
                        {
                            Id = 1130,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Référent",
                            Tjm = 1000m
                        },
                        new
                        {
                            Id = 1131,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Référent",
                            Tjm = 600m
                        },
                        new
                        {
                            Id = 1132,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Référent",
                            Tjm = 767m
                        },
                        new
                        {
                            Id = 1133,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Référent",
                            Tjm = 460m
                        },
                        new
                        {
                            Id = 1140,
                            Category = "Agences",
                            Location = "TJM Paris",
                            Profile = "Manager",
                            Tjm = 1050m
                        },
                        new
                        {
                            Id = 1141,
                            Category = "Agences",
                            Location = "CJM Paris",
                            Profile = "Manager",
                            Tjm = 630m
                        },
                        new
                        {
                            Id = 1142,
                            Category = "Agences",
                            Location = "TJM Région",
                            Profile = "Manager",
                            Tjm = 833m
                        },
                        new
                        {
                            Id = 1143,
                            Category = "Agences",
                            Location = "CJM Région",
                            Profile = "Manager",
                            Tjm = 500m
                        },
                        new
                        {
                            Id = 2000,
                            Category = "CES Log",
                            Location = "TJM CES",
                            Profile = "Architecte",
                            Tjm = 652m
                        },
                        new
                        {
                            Id = 2001,
                            Category = "CES Log",
                            Location = "CJM CES",
                            Profile = "Architecte",
                            Tjm = 391m
                        },
                        new
                        {
                            Id = 2002,
                            Category = "CES Log",
                            Location = "PRCS CES",
                            Profile = "Architecte",
                            Tjm = 555m
                        },
                        new
                        {
                            Id = 2010,
                            Category = "CES Log",
                            Location = "TJM CES",
                            Profile = "Chef de Projet",
                            Tjm = 603m
                        },
                        new
                        {
                            Id = 2011,
                            Category = "CES Log",
                            Location = "CJM CES",
                            Profile = "Chef de Projet",
                            Tjm = 362m
                        },
                        new
                        {
                            Id = 2012,
                            Category = "CES Log",
                            Location = "PRCS CES",
                            Profile = "Chef de Projet",
                            Tjm = 514m
                        },
                        new
                        {
                            Id = 2020,
                            Category = "CES Log",
                            Location = "TJM CES",
                            Profile = "Dev confirmé",
                            Tjm = 570m
                        },
                        new
                        {
                            Id = 2021,
                            Category = "CES Log",
                            Location = "CJM CES",
                            Profile = "Dev confirmé",
                            Tjm = 342m
                        },
                        new
                        {
                            Id = 2022,
                            Category = "CES Log",
                            Location = "PRCS CES",
                            Profile = "Dev confirmé",
                            Tjm = 486m
                        },
                        new
                        {
                            Id = 2030,
                            Category = "CES Log",
                            Location = "TJM CES",
                            Profile = "Dev junior",
                            Tjm = 417m
                        },
                        new
                        {
                            Id = 2031,
                            Category = "CES Log",
                            Location = "CJM CES",
                            Profile = "Dev junior",
                            Tjm = 250m
                        },
                        new
                        {
                            Id = 2032,
                            Category = "CES Log",
                            Location = "PRCS CES",
                            Profile = "Dev junior",
                            Tjm = 355m
                        },
                        new
                        {
                            Id = 2040,
                            Category = "CES Log",
                            Location = "TJM CES",
                            Profile = "Manager",
                            Tjm = 915m
                        },
                        new
                        {
                            Id = 2041,
                            Category = "CES Log",
                            Location = "CJM CES",
                            Profile = "Manager",
                            Tjm = 549m
                        },
                        new
                        {
                            Id = 2042,
                            Category = "CES Log",
                            Location = "PRCS CES",
                            Profile = "Manager",
                            Tjm = 780m
                        },
                        new
                        {
                            Id = 3000,
                            Category = "CES Infra",
                            Location = "TJM CES",
                            Profile = "Technicien Support N1",
                            Tjm = 180m
                        },
                        new
                        {
                            Id = 3001,
                            Category = "CES Infra",
                            Location = "CJM CES",
                            Profile = "Technicien Support N1",
                            Tjm = 180m
                        },
                        new
                        {
                            Id = 3010,
                            Category = "CES Infra",
                            Location = "TJM CES",
                            Profile = "Technicien Support N2",
                            Tjm = 235m
                        },
                        new
                        {
                            Id = 3011,
                            Category = "CES Infra",
                            Location = "CJM CES",
                            Profile = "Technicien Support N2",
                            Tjm = 235m
                        },
                        new
                        {
                            Id = 3020,
                            Category = "CES Infra",
                            Location = "TJM CES",
                            Profile = "Ingénieur Support N3",
                            Tjm = 325m
                        },
                        new
                        {
                            Id = 3021,
                            Category = "CES Infra",
                            Location = "CJM CES",
                            Profile = "Ingénieur Support N3",
                            Tjm = 325m
                        },
                        new
                        {
                            Id = 3030,
                            Category = "CES Infra",
                            Location = "TJM CES",
                            Profile = "TAM",
                            Tjm = 360m
                        },
                        new
                        {
                            Id = 3031,
                            Category = "CES Infra",
                            Location = "CJM CES",
                            Profile = "TAM",
                            Tjm = 360m
                        });
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectConsultant", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfilRow", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfileMonthly", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Data.ProjectProfilRow", null)
                        .WithMany()
                        .HasForeignKey("ProfilRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExakisNeliteTSP.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
