// <auto-generated />
using System;
using ExakisNeliteTSP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExakisNeliteTSP.Migrations
{
    [DbContext(typeof(TspDbContext))]
    [Migration("20250910073026_Add_ProjectProfilRows")]
    partial class Add_ProjectProfilRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectConsultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ProjectConsultants");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfilRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeJh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cjm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("FraisDeplacementSiCession")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal?>("Prcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Profil")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TciOverPrcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tjm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProfilRows");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyDirector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchitectCds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchitectInternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackProjectManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<decimal?>("ContractAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractBackAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractCaBack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("ProjectLead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposalRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RemiseTjmPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalesRep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectConsultant", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfilRow", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
