// <auto-generated />
using System;
using ExakisNeliteTSP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExakisNeliteTSP.Migrations
{
    [DbContext(typeof(TspDbContext))]
    [Migration("20250917100436_SeedTjmDefaults")]
    partial class SeedTjmDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectConsultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("ProjectConsultants");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfilRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeJh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cjm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("FraisDeplacementSiCession")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal?>("Prcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Profil")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TciOverPrcs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tjm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProfilRows");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfileMonthly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChargeJh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<int>("ProfilRowId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfilRowId");

                    b.HasIndex("ProjectId", "ProfilRowId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ProjectProfileMonthlies");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyDirector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchitectCds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchitectInternal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackProjectManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<decimal?>("ContractAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractBackAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ContractCaBack")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("ProjectLead")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposalRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RemiseTjmPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("SalesRep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceLineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.ProjectTjmItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tjm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Category", "Profile", "Location")
                        .IsUnique();

                    b.ToTable("ProjectTjmItems");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Models.ReferentielTjmItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Tjm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Profile", "Location")
                        .IsUnique();

                    b.ToTable("ReferentielTjmItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Agences",
                            Location = "Paris",
                            Profile = "Consultant Junior",
                            Tjm = 500m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Agences",
                            Location = "Province",
                            Profile = "Consultant Junior",
                            Tjm = 300m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Agences",
                            Location = "Région",
                            Profile = "Consultant Junior",
                            Tjm = 261m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Agences",
                            Location = "Paris",
                            Profile = "Consultant",
                            Tjm = 583m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Agences",
                            Location = "Province",
                            Profile = "Consultant",
                            Tjm = 300m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Agences",
                            Location = "Région",
                            Profile = "Consultant",
                            Tjm = 283m
                        },
                        new
                        {
                            Id = 100,
                            Category = "CES Log",
                            Location = "CES",
                            Profile = "Architecte",
                            Tjm = 652m
                        },
                        new
                        {
                            Id = 101,
                            Category = "CES Log",
                            Location = "CES",
                            Profile = "Chef de Projet",
                            Tjm = 603m
                        },
                        new
                        {
                            Id = 102,
                            Category = "CES Log",
                            Location = "CES",
                            Profile = "Dev confirmé",
                            Tjm = 570m
                        },
                        new
                        {
                            Id = 103,
                            Category = "CES Log",
                            Location = "CES",
                            Profile = "Dev junior",
                            Tjm = 417m
                        },
                        new
                        {
                            Id = 104,
                            Category = "CES Log",
                            Location = "CES",
                            Profile = "Manager",
                            Tjm = 915m
                        },
                        new
                        {
                            Id = 200,
                            Category = "CES Infra",
                            Location = "CES",
                            Profile = "Technicien Support N1",
                            Tjm = 180m
                        },
                        new
                        {
                            Id = 201,
                            Category = "CES Infra",
                            Location = "CES",
                            Profile = "Technicien Support N2",
                            Tjm = 235m
                        },
                        new
                        {
                            Id = 202,
                            Category = "CES Infra",
                            Location = "CES",
                            Profile = "Ingénieur Support N3",
                            Tjm = 325m
                        },
                        new
                        {
                            Id = 203,
                            Category = "CES Infra",
                            Location = "CES",
                            Profile = "TAM",
                            Tjm = 360m
                        });
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectConsultant", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfilRow", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ExakisNeliteTSP.Data.ProjectProfileMonthly", b =>
                {
                    b.HasOne("ExakisNeliteTSP.Data.ProjectProfilRow", null)
                        .WithMany()
                        .HasForeignKey("ProfilRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExakisNeliteTSP.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
